# Generated by Django 6.1.1 on 2026-09-29 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('824709de-31c6-4dcb-8740-7a7209512301'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('source', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('TELEGRAM', 'Telegram'), ('WEBSITE', 'Website'), ('FACEBOOK', 'Facebook'), ('REFERRAL', 'Referral'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'new'), ('CONTACTED', 'contacted'), ('QUALIFIED', 'qualified'), ('WON', 'won'), ('LOST', 'lost')], default='NEW', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
